/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline": "#86948a",
        "on-secondary-container": "#b0b2ff",
        "tertiary": "#ffb2b7",
        "primary-container": "#10b981",
        "inverse-surface": "#e3e1ec",
        "on-error": "#690005",
        "on-background": "#e3e1ec",
        "tertiary-fixed-dim": "#ffb2b7",
        "outline-variant": "#3c4a42",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#92002a",
        "primary": "#4edea3",
        "surface-bright": "#383941",
        "background": "#12131a",
        "primary-fixed": "#6ffbbe",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#33343c",
        "on-surface": "#e3e1ec",
        "tertiary-fixed": "#ffdadb",
        "on-primary": "#003824",
        "surface": "#12131a",
        "on-primary-container": "#00422b",
        "tertiary-container": "#ff7886",
        "on-surface-variant": "#bbcabf",
        "surface-variant": "#33343c",
        "secondary-fixed-dim": "#c0c1ff",
        "inverse-primary": "#006c49",
        "on-tertiary-container": "#780021",
        "error": "#ffb4ab",
        "surface-tint": "#4edea3",
        "on-secondary-fixed": "#07006c",
        "on-secondary": "#1000a9",
        "primary-fixed-dim": "#4edea3",
        "inverse-on-surface": "#2f3038",
        "surface-container-low": "#1a1b22",
        "on-primary-fixed": "#002113",
        "surface-container": "#1e1f26",
        "surface-container-lowest": "#0d0e15",
        "on-primary-fixed-variant": "#005236",
        "secondary-container": "#3131c0",
        "surface-container-high": "#292931",
        "secondary-fixed": "#e1e0ff",
        "on-tertiary-fixed": "#40000d",
        "on-tertiary": "#67001b",
        "secondary": "#c0c1ff",
        "on-secondary-fixed-variant": "#2f2ebe",
        "surface-dim": "#12131a",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "gutter-desktop": "1.5rem",
        "margin-tablet": "1.5rem",
        "space-md": "0.75rem",
        "margin-desktop": "2rem",
        "space-lg": "1.25rem",
        "space-sm": "0.5rem",
        "space-xl": "2rem",
        "margin": "1rem",
        "space-2xl": "3rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
      },
      fontFamily: {
        "body-sm": ["Geist", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "label-data-md": ["'JetBrains Mono'", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "label-data-lg": ["'JetBrains Mono'", "monospace"],
        "headline-xl-mobile": ["Geist", "sans-serif"],
        "label-data-sm": ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "body-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "-0.006em", fontWeight: "400" }],
        "headline-xl": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.035em", fontWeight: "600" }],
        "label-data-md": ["0.875rem", { lineHeight: "1.125rem", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.025em", fontWeight: "600" }],
        "body-lg": ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.011em", fontWeight: "400" }],
        "headline-md": ["1.125rem", { lineHeight: "1.5rem", letterSpacing: "-0.015em", fontWeight: "500" }],
        "label-data-lg": ["1.25rem", { lineHeight: "1.5rem", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-xl-mobile": ["1.75rem", { lineHeight: "2.125rem", letterSpacing: "-0.025em", fontWeight: "600" }],
        "label-data-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

